name: Run tests and linter

on: [push, pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.x'
    - name: Install dependencies
      run: go mod vendor
    - name: Run tests
      run: go test -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.x'
    - name: Install dependencies
      run: go mod vendor
    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45